### ISSUE TITLE
不能解析license

### ISSUE THREAD

**Issue by wanbangshucheng1** [CrymanChen/WKS-KEYS#13]
![YK{ZC5_ 7`ELR}JJD%K8KQP](https://github.com/user-attachments/assets/14174d02-fab2-4254-8b5f-d415e35d8a7d)

**Comment by CrymanChen** [comment]
1. 开局一张图，其他信息全靠我猜？
2. 我已在[使用方法](https://github.com/CrymanChen/WKS-KEYS#usage-chinese-simplified)中声明：

> 本项目需要一定的专业知识(A bit technical), 如果您对该领域不了解, 请不要进行尝试, 我亦不会对相应问题进行解答

**如果您对该领域不了解，请不要进行尝试**，谢谢
不是我的repo有问题，而是你不会用 :)
3. It works perfectly. **But I'm not going to disclose the key**.
![20241013-005113](https://github.com/user-attachments/assets/4c1103c9-37c4-426a-b29c-b376a17e3e38)

Also, this issue is to be locked and closed.
